---
- name: Install MariaDB client
  hosts: db_clients
  become: true
  gather_facts: false
  tasks:
    - name: Install client software
      ansible.builtin.dnf:
        name: mariadb
        state: present

- name: Install MariaDB server
  hosts: db_servers
  become: true
  gather_facts: false
  tasks:
    - name: Install software
      ansible.builtin.dnf:
        name:
          - mariadb-server  # MariaDB Server software
          - python3-PyMySQL # Required by community.mysql
        state: present

    - name: Start and enable service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Add firewall access
      ansible.posix.firewalld:
        service: mysql
        permanent: true
        state: enabled
        immediate: true
