---
- name: Nginx web server deployment
  hosts: webserver
  become: true

  roles:
    - name: redhat.rhel_system_roles.selinux
      selinux_fcontexts:
        - target: '/srv/serverc(/.*)?'
          setype: 'httpd_sys_content_t'
          state: present
        - target: '/srv/virtual(/.*)?'
          setype: 'httpd_sys_content_t'
          state: present

  tasks:
    - name: Latest software installed for nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
      notify: Restart nginx

    - name: Web content is in place
      ansible.builtin.import_tasks: deploy_content.yml

    - name: Set up nginx serverblock
      ansible.builtin.template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/conf.d/nginx.conf"

    - name: Set up nginx serverblock
      ansible.builtin.template:
        src: "nvirtual.conf.j2"
        dest: "/etc/nginx/conf.d/virtual.conf"

      notify: Reload nginx
    - name: Firewall ports are open
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - https
        - http

    - name: Nginx is enabled and started
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted