---
- name: Configure a samba share
  hosts: smb
  become: true
  gather_facts: false
  vars:
    smb_pkg: samba
    smb_srv: smb
    firewall_srv: samba
  vars_files:
    - smb_vars.yml

  tasks:
    - name: Install Samba software
      ansible.builtin.dnf:
        name: "{{ smb_pkg }}"
        state: present

    - name: Create the Linux group
      ansible.builtin.group:
        name: "{{ allowed_group }}"
        system: true

    - name: Create the Linux user that mounts the shared directory
      ansible.builtin.user:
        name: "{{ samba_usermount }}"
        shell: /sbin/nologin
        create_home: false
        system: true

    - name: Create the Linux users for Samba
      ansible.builtin.user:
        name: "{{ item['name'] }}"
        shell: /sbin/nologin
        groups:
          - "{{ allowed_group }}"
      loop: "{{ samba_users }}"
      no_log: true

    - name: Create the Samba user for Samba mounting
      ansible.builtin.command: smbpasswd -s -a {{ samba_usermount }}
      args:
        stdin: "{{ samba_passmount }}\n{{ samba_passmount }}"

    - name: Create the Samba users
      ansible.builtin.command: smbpasswd -s -a {{ item['name'] }}
      args:
        stdin: "{{ item['password'] }}\n{{ item['password'] }}"
      loop: "{{ samba_users }}"
      no_log: true

    - name: Create the shared directory
      ansible.builtin.file:
        path: "{{ smb_dir }}"
        owner: root
        group: "{{ allowed_group }}"
        mode: '2775'
        state: directory
        setype: samba_share_t

    - name: Configure the shared directory
      ansible.builtin.template:
        src: templates/smb.conf.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: '0644'
        setype: samba_etc_t
      notify: Reload service

    - name: Ensure Samba server service is enabled and running
      ansible.builtin.service:
        name: "{{ smb_srv }}"
        state: started
        enabled: true

    - name: Ensure firewall allows Samba server service
      ansible.posix.firewalld:
        service: "{{ firewall_srv }}"
        state: enabled
        immediate: true
        permanent: true

  handlers:
    - name: Reload service
      ansible.builtin.service:
        name: "{{ smb_srv }}"
        state: reloaded
