---
- name: Access a Samba share
  hosts: clients
  become: true
  gather_facts: false
  vars:
    client_pkg: cifs-utils
    mount_point: /developments
    smb_name: smbshare
  vars_files:
   - smb_vars.yml

  tasks:
    - name: Install Samba software
      ansible.builtin.dnf:
        name: "{{ client_pkg }}"
        state: present

    - name: The credential file exists
      ansible.builtin.copy:
        content: "username={{ samba_usermount }}\n\
                  password={{ samba_passmount }}\n"
        dest: /etc/samba/creds.txt
        owner: root
        group: root
        mode: '0600'
      no_log: true

    - name: The Samba share is mounted
      ansible.posix.mount:
        path: "{{ mount_point }}"
        src: "//serverd.lab.example.com/{{ smb_name }}"
        opts: "credentials=/etc/samba/creds.txt,multiuser,seal"
        state: mounted
        fstype: cifs

    - name: Create Linux users
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        password: "{{ item.password | \
                   password_hash('sha512', 'redhatsalt') }}"
      loop: "{{ samba_users }}"
      no_log: true
