---
- name: Configure primary nameserver
  hosts: primary_dns
  remote_user: devops
  become: true

  tasks:
    - name: Install BIND9
      ansible.builtin.dnf:
        name: bind
        state: present

    - name: Copy primary config file
      ansible.builtin.copy:
        src: files/primary-named.conf
        dest: /etc/named.conf
        owner: root
        group: named
        mode: 0640
      notify:
        - reload_named

    - name: Copy forward zone file to primary
      ansible.builtin.copy:
        src: files/primary-backend.lab.example.com.zone
        dest: /var/named/backend.lab.example.com.zone
        owner: root
        group: named
        mode: 0640
      notify:
        - reload_named

    - name: Copy reverse zone file to primary
      ansible.builtin.copy:
        src: files/primary-192.168.0.zone
        dest: /var/named/192.168.0.zone
        owner: root
        group: named
        mode: 0640
      notify:
        - reload_named

    - name: Copy backend config file (for zones)
      ansible.builtin.copy:
        src: files/primary-named.backend.conf
        dest: /etc/named.backend.conf
        owner: root
        group: named
        mode: 0640
      notify:
        - reload_named

    - name: Allow dns service on firewall
      ansible.posix.firewalld:
        service: dns
        state: enabled
        immediate: true
        permanent: true

    - name: Ensure named is running and enabled
      ansible.builtin.service:
        name: named
        state: started
        enabled: true

  handlers:
    - name: reload_named
      ansible.builtin.service:
        name: named
        state: reloaded
