---
- name: Install MariaDB server
  hosts: db_servers
  become: true

  tasks:
    - name: Install mariadb-server package
      ansible.builtin.dnf:
        name: mariadb-server
        state: present

    - name: Enable and start mariadb
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Firewall permits mysql service
      ansible.posix.firewalld:
        service: mysql
        permanent: true
        state: enabled
        immediate: true

    - name: Install package required by the community.mysql collection
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: present
