---
- name: Restore inventory database if not present
  hosts: db_servers
  become: true

  tasks:
    - name: Make sure inventory database exists
      community.mysql.mysql_db:
        name: inventory
        state: present
      register: inventory_present

    - name: Is inventory database backup present?
      ansible.builtin.stat:
        path: /srv/inventory-database.sql
      register: inventory_bkup

    - name: Copy database backup file to host if not present
      ansible.builtin.copy:
        src: files/inventory-database.sql
        dest: /srv
      when:
        - inventory_present['changed'] is true
        - inventory_bkup['stat']['exists'] is false

    - name: Restore inventory backup data
      community.mysql.mysql_db:
        name: inventory
        state: import
        target: /srv/inventory-database.sql
      when: inventory_present['changed'] is true
