download_url: https://hub.lab.example.com/api/galaxy/v3/plugin/ansible/content/community/collections/artifacts/community-mysql-3.12.0.tar.gz
format_version: 1.0.0
name: mysql
namespace: community
server: https://hub.lab.example.com/api/galaxy/content/community/
signatures: []
version: 3.12.0
version_url: /api/galaxy/content/community/v3/plugin/ansible/content/community/collections/index/community/mysql/versions/3.12.0/
