---
- name: Ensure /data is mounted from serverd iSCSI target
  hosts: servera.lab.example.com
  become: true
  tasks:
    - name: The iscsi-initiator-utils package is installed
      ansible.builtin.dnf:
        name: iscsi-initiator-utils
        state: present

    - name: The IQN is set for the initiator
      ansible.builtin.template:
        dest: /etc/iscsi/initiatorname.iscsi
        src: templates/initiatorname.iscsi.j2
        mode: "0644"
        owner: root
        group: root
      notify: Restart iscsid

    # Forces the handler to run so that the iscsid service is restarted
    # and is aware of the new initiator IQN
    - name: Restart iscsid if necessary
      ansible.builtin.meta: flush_handlers

    - name: The iSCSI target is discovered and available
      community.general.open_iscsi:
        portal: 172.25.250.13
        port: 3260
        target: iqn.2025-01.com.example:serverd
        discover: true
        login: true
      register: target

    - name: Display the discovered devices
      ansible.builtin.debug:
        var: target['devicenodes']

    - name: The new device is formatted and mounted under /data
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.storage
      vars:
        storage_volumes:
          - name: devdata
            state: present
            type: disk
            disks:
              - "{{ target['devicenodes'][0] }}"
            mount_point: /data
            fs_type: xfs
            mount_options: _netdev

  handlers:
    - name: Restart iscsid
      ansible.builtin.service:
        name: iscsid
        state: restarted
